### ISSUE TITLE
feature request - option to change the particles to the scene's worldspace

### ISSUE THREAD

**Issue by code-matt** [fazeaction/three-gpu-particle-system#1]
First off, wanted to say.. I explored at least four different Three particle frameworks, for a project I am working on. I think this one is well thought out and easiest to use. Its also very performant from my tests so far.

I am not sure I phrased the request 100% correct.. basically, the current way the particles travel with an emitter is great for plenty of effects. But, would there be a chance of getting an option to have the particles stay in the scenes worldspace once they are emitted though? 

Example: For a fireball, you want the flame/smoke trail to stay in place as the emitter zooms along.(they should still respect their world accel value though so it can slowly rise as well)

If that one is too easy for you, another option for particles to inherit the current acceleration of the parent object that the emitter is attached to would be awesome. As well as specifying just how mich should be inherited 0 - 200% :D

**Comment by fazeaction** [comment]
I am not sure whether I understood the question, but can you show me an example with the animation that you are trying to achieve?

Anyway, in this example you have a trail by pressing letter "t" (https://www.khronos.org/registry/webgl/sdk/demos/google/particles/). At birth time, you can modify the params per particle but it’s up to you to figure out the correct vector. After the data is uploaded to the GPU, you can’t modify it and the animation is time based, in other words, the particle always follow asigned vectors (no random walks, no direction changes) and only affect by world forces that are applied to all the particles of the emitter. Please, check the source code in the example folder to understand how to make per particles change (proof o trail) .

**Comment by code-matt** [comment]
Sorry I did not investigate the Trail one more, that example is exactly what I was talking about as far as them living in the scene space. Thanks! 

That is too bad about the acceleration, I had figured out the initial state stuff but was unsure about the rest, shader code kind of scares me. I guess that is partly why this is more performant than some other particle frameworks though :)
