### ISSUE TITLE
onBeforeREnder is not working with the latest version of threejs

### ISSUE THREAD

**Issue by arturitu** [fazeaction/three-gpu-particle-system#6]
If I update the threejs version to 0.136.0 stop working becase dispatch this error: "Uncaught TypeError: material.onBeforeRender is not a function".
I'm not sure if is because I'm updating the system wrong or it is something related with the way you draw the particles.

**Comment by fazeaction** [comment]
Hi Arturo! thanks for reporting this bug. I was doing a silly mistake publishing the package with threejs as a dependency. If for some reason you are importing three in your project you will ended with duplicate versions of three. 
Now is solved, please update your three.tdl.particle.system to version 1.0.3. That removes the threejs version library inside the package and will use your version 136. Please, let me know if is solved and you can close the issue.

**Comment by arturitu** [comment]
Fixed, thanks!
